staff_project/staff_project/urls.py
from django.contrib import admin
from django.urls import path

from staff_app.views import department, staff, mobile, good, admin, account, task

urlpatterns = [
    # path('admin/', admin.site.urls),

    # 部门管理
    path('department_list/', department.department_list),
    path('department_add/', department.department_add),
    path('department_delete/', department.department_delete),
    path('department_edit/<int:nid>', department.department_edit),
    # 员工管理
    path('staff_list/', staff.staff_list),
    path('staff_add/', staff.staff_add),
    path('modelform_staff_add/', staff.modelform_staff_add),
    path('staff_edit/<int:nid>', staff.staff_edit),
    path('staff_delete/<int:nid>', staff.staff_delete),
    # 靓号管理
    path("mobile_list/", mobile.mobile_list),
    path("mobile_add/", mobile.mobile_add),
    path('mobile_edit/<int:nid>', mobile.mobile_edit),
    path("mobile_delete/<int:nid>", mobile.mobile_delete),
    # 商品管理
    path('good_list/', good.good_list),
    path('good_add/', good.good_add),
    path('good_edit/<int:nid>', good.good_edit),
    path('good_delete/<int:nid>', good.good_delete),
    # 管理员的管理
    path('admin_list/', admin.admin_list),
    path('admin_add/', admin.admin_add),
    path('admin_edit/<int:nid>', admin.admin_edit),
    path('admin_delete/<int:nid>', admin.admin_delete),
    path('admin_reset/<int:nid>', admin.admin_reset),
    # 登录和注销
    path('login/', account.login),
    path('logout/', account.logout),
    path('image_code/', account.image_code),
    # 任务管理
    path('task_list/', task.task_list),
    path('task_ajax/', task.task_ajax),
    path('task_add/', task.task_add),
]

staff_project/staff_app/models.py
from django.db import models


class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    # 这是我们用ForeignKey关联表的时候，他显示的是一个对象，我们使用了这个就能让他显示我们的username
    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""                """verbose_name：对这一列经行注解"""
    title = models.CharField(verbose_name="部门标题", max_length=32)

    # 这是我们用ForeignKey关联表的时候，他显示的是一个对象，我们使用了这个就能让他显示我们的title
    def __str__(self):
        return self.title


class StaffInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    salary = models.DecimalField(verbose_name="工资", max_digits=8, decimal_places=2, default=0)
    # entry_time = models.DateTimeField(verbose_name="入职时间")
    entry_time = models.DateField(verbose_name="入职时间")
    # to="Department"：与哪个表关联，，to_field="id"：与表中的哪一列关联
    # 在使用Foreignkey时，staff_depart在数据库生成的时候，会自动变为staff_department_id
    # on_delete=models.CASCADE,当部门表被删除，员工表与之相关的全部删除
    # null = True, blank = True,表允许为空，on_delete=models.SET_NULL，当部门表被删除，员工表与之相关的全部置空
    staff_department = models.ForeignKey(verbose_name="所属部门", to="Department", to_field="id", null=True, blank=True,
                                         on_delete=models.CASCADE)
    gender_choices = ((1, "男"), (2, "女"))  # 在django中做的约束
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)


class MobileNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=11)  # 后面会对手机号进行正则表达式和搜索，所以这里用CharField
    # 想要允许为空 null=True, blank=True
    price = models.IntegerField(verbose_name="价格", default=0)
    # 靓号级别
    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)  # default=1 : 默认为 1

    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


class GoodInfo(models.Model):
    name = models.CharField(verbose_name="商品名称", max_length=8)
    price = models.DecimalField(verbose_name="商品价格", max_digits=5, decimal_places=2, default=0)
    color_choices = (
        (1, "红色"),
        (2, "绿色")
    )
    color = models.SmallIntegerField(verbose_name="商品的颜色", choices=color_choices, default=1)


class Task(models.Model):
    """任务"""
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    # on_delete=models.CASCADE级联删除
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)

staff_project/staff_app/views/account.py
from io import BytesIO

from django import forms
from django.shortcuts import render, HttpResponse, redirect

from staff_app import models
from staff_app.utils.encrypt import md5
from staff_app.utils.bootstrap import BootStrapForm
from staff_app.utils.code import check_code


# 本来这个括号里面应该继承forms.Form,但是utils文件下的bootstrap.py中的BootStrapForm已经继承了forms.Form
class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(),
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(),
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )

    # 定义一个钩子方法
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """登陆"""
    if request.method == "GET":
        form = LoginForm()  # 实例化我们写的类
        return render(request, "login.html", {"form": form})
    else:
        form = LoginForm(data=request.POST)  # 获取到用户提交的数据
        if form.is_valid():  # 判断是否验证成功
            # 这里是验证码-验证
            user_input_code = form.cleaned_data.pop('code')
            code = request.session.get('image_code', "")
            if code.upper() != user_input_code.upper():
                form.add_error("code", "验证码错误")
                return render(request, 'login.html', {'form': form})

            # 这里是用户名和密码-验证
            # print(form.cleaned_data)  # 验证成功，获取到的用户名和密码
            # 去数据库校验用户名和密码是否正确
            # admin_object = models.Admin.objects.filter(username=form.cleaned_data['username'],password=form.cleaned_data['password']).first()
            # 这里的筛选条件可以是一个字典，我们的form.cleaned_data获取到的就是用户输入的字典，但是需要加上连个**
            admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
            if not admin_object:  # 如果是空，就不是一个对象，是none
                form.add_error("password", "用户名或密码错误")  # 主动添加错误
                return render(request, "login.html", {"form": form})
            else:  # 用户名和密码正确
                # 网站生成随机字符串，写到用户浏览器的cookie中，再写入到网站的session中
                # request.session["info"] = admin_object.username  # 这一步直接完成了生成随机字符串，写到用户浏览器的cookie中，再将用户名写入到网站的session中
                request.session["info"] = {"id": admin_object.id,
                                           "name": admin_object.username}  # 这里写入到网站的session中的info是一个字典，包含id和name
                return redirect("/admin_list/")
        else:
            return render(request, "login.html", {"form": form})  # 验证失败，返回这个，显示错误信息


def image_code(request):
    """ 生成图片验证码 """
    # 调用pillow函数，生成图片
    img, code_string = check_code()
    print(code_string)
    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string

    # 以前我们用脚本产生的图片验证码是张图片，返还到前端还要再读取，很麻烦
    # 现在我们利用 BytesIO() 相当于 内存中的一个对象(可以理解为把图片直接写入内存中)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def logout(request):
    """注销"""

    request.session.clear()
    return redirect('/login/')

staff_project/staff_app/views/admin.py
import time  # 先导入内置模块，规律是短的在上面

from django import forms  # 中间导入第三方已安装的模块
from django.shortcuts import render, HttpResponse, redirect

from staff_app import models  # 最后导入我们自定义的模块
from staff_app.utils.pagination import Pagination
from staff_app.utils.form import StaffModelFrom, MobileModelForm

from django import forms
from django.core.exceptions import ValidationError
from staff_app.utils.bootstrap import BootStrapModelForm
from staff_app.utils.encrypt import md5


def admin_list(request):
    """管理员列表"""

    # 检查用户是否已经登录，登录则可以访问，未登录则跳转会登录页码
    # 用户发来请求，获取用户浏览器cookie随机字符串，和网站session中做对比
    info = request.session.get("info")
    if not info:
        return redirect("/login/")

    # 构造搜索
    data_dict = {}
    search_data = request.GET.get('num', "")
    if search_data:
        data_dict["username__contains"] = search_data

    # 根据搜索条件取数据库获取
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_object = Pagination(request, queryset, page_size=4)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
        "search_data": search_data
    }
    return render(request, "admin_list.html", context)


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ["username", "password"]
        widgets = {
            "password": forms.PasswordInput(render_value=True),
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    # 钩子方法
    def clean_confirm_password(self):
        print(self.cleaned_data)
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致")

        # 返回什么，此字段以后保存到数据库就是什么
        return confirm


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value=True)
    )

    class Meta:
        model = models.Admin
        fields = ['password', 'confirm_password']
        widgets = {
            "password": forms.PasswordInput(render_value=True)
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        md5_pwd = md5(pwd)

        # 去数据库校验当前密码与新输入的密码是否一致
        exists = models.Admin.objects.filter(id=self.instance.pk, password=md5_pwd).exists()
        if exists:
            raise ValidationError("密码不能与之前的相同")

    # 钩子方法
    def clean_confirm_password(self):
        print(self.cleaned_data)
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd:
            raise ValidationError("密码不一致")

        # 返回什么，此字段以后保存到数据库就是什么
        return confirm


def admin_reset(request, nid):
    """重置密码"""
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, "error.html", {"msg": "数据不存在"})

    title = "重置密码"

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, "change.html", {"form": form, "title": title})
    else:
        form = AdminResetModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect("/admin_list/")
        else:
            return render(request, "change.html", {"form": form, "title": title})
            # return HttpResponse("出现错误")


def admin_add(request):
    """添加管理员"""
    title = "新建管理员"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, "change.html", {"form": form, "title": title})
    else:
        form = AdminModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/admin_list/")
        else:
            return render(request, "change.html", {"form": form, "title": title})


def admin_edit(request, nid):
    """编辑管理员"""
    # 如果能搜到，则是获取到的是一个对象，搜不到则是None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, "error.html", {"msg": "数据不存在"})

    title = "编辑管理员"
    if request.method == "GET":
        form = AdminEditModelForm(instance=row_object)  # 显示默认值，instance=rowobject
        return render(request, "change.html", {"form": form, "title": title})
    else:
        form = AdminEditModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect("/admin_list/")
        else:
            return render(request, "change.html", {"form": form, "title": title})


def admin_delete(request, nid):
    """删除管理员"""
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin_list/")

staff_project/staff_app/views/department.py
from django.shortcuts import render, HttpResponse, redirect
from staff_app import models
from staff_app.utils.pagination import Pagination
from staff_app.utils.form import StaffModelFrom, MobileModelForm
from django import forms


def department_list(request):
    """部门列表"""
    # queryset是[对象(一行数据)，对象，对象]
    # queryset = models.Department.objects.all()
    queryset = models.Department.objects.all()

    page_object = Pagination(request, queryset, page_size=4)

    context = {
        "data_list": page_object.page_queryset,
        "page_string": page_object.html()
    }

    return render(request, "department_list.html", context)


def department_add(request):
    """添加部门"""
    if request.method == "GET":
        return render(request, 'department_add.html')
    title = request.POST.get("title")
    # 保存到数据库
    models.Department.objects.create(title=title)
    # 重定向回部门列表
    return redirect("/department_list/")


def department_delete(request):
    """删除部门"""
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()
    return redirect("/department_list/")


def department_edit(request, nid):
    """编辑部门(修改部门)"""
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "department_edit.html", {"row_object": row_object})
    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)

    return redirect("/department_list/")

staff_project/staff_app/views/good.py
from django.shortcuts import render, HttpResponse, redirect
from staff_app import models
from staff_app.utils.pagination import Pagination
from staff_app.utils.form import StaffModelFrom, MobileModelForm, GoodModelForm
from django import forms


def good_list(request):
    """商品列表"""
    queryset = models.GoodInfo.objects.all()
    page_object = Pagination(request, queryset, page_size=2)
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html()  # 生成的页码
    }
    return render(request, "good_list.html", context)


def good_add(request):
    """新增商品"""
    if request.method == "GET":
        form = GoodModelForm()
        return render(request, "good_add.html", {"form": form})

    form = GoodModelForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        form.save()
        return redirect("/good_list/")
    return render(request, 'good_add.html', {"form": form})


def good_edit(request, nid):
    """编辑商品"""
    row_object = models.GoodInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        form = GoodModelForm(instance=row_object)
        return render(request, "good_edit.html", {"form": form})
    else:
        form = GoodModelForm(data=request.POST, instance=row_object)
        if form.is_valid():
            form.save()
            return redirect("/good_list/")
        else:
            return render(request, "good_edit.html", {"form": form})


def good_delete(request, nid):
    """删除商品"""
    models.GoodInfo.objects.filter(id=nid).delete()
    return redirect("/good_list/")

staff_project/staff_app/views/task.py
import json
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt

from django import forms
from staff_app import models
from staff_app.utils.bootstrap import BootStrapModelForm


class TaskModelForm(BootStrapModelForm):
    class Meta:
        model = models.Task
        fields = "__all__"
        widgets = {
            # "detail":forms.TextInput
            "detail": forms.Textarea
        }


def task_list(request):
    """任务管理列表"""

    form = TaskModelForm()  # 实例化我们自定义的类
    return render(request, "task_list.html", {"form": form})


@csrf_exempt
def task_ajax(request):
    print(request.GET)
    print(request.POST)
    data_dict = {"status": True, "data": [11, 22, 33, 44]}
    return HttpResponse(json.dumps(data_dict))


@csrf_exempt
def task_add(request):
    print(request.POST)

    # 对用户发过来的数据进行校验（用modelform进行校验）
    form = TaskModelForm(data=request.POST)
    if form.is_valid():  # 如果校验成果执行form.save()
        form.save()  # 将用户提交的数据保存到数据库
        # 通过ajax发送请求，如果成功了，不嫩返回redirect，要返回一个JSON表示状态是True
        data_dict = {"status": True}
        return HttpResponse(json.dumps(data_dict))  # 将python对象转换成json对象，生成的是字符串
    else:
        error = form.errors  # form.errors包含了全部的错误信息，as_json将错误信息转化为json格式
        # 通过ajax发送请求，如果失败了，不嫩返回redirect，要返回一个JSON表示状态是True
        print(error)
        data_dict = {"status": False, "error": error}
        return HttpResponse(json.dumps(data_dict))

staff_project/staff_app/templates/change.html
{% extends 'layout.html' %}


{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{title}}</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

staff_project/staff_app/templates/department_add.html
{% extends 'layout.html' %}
{% block content %}
<!--新建部门-->
<div>
    <div class="container">
        <!--面板里面套表单-->
        <div class="panel panel-default">
            <div class="panel-heading">新建部门</div>
            <div class="panel-body">
                <!--这是表单,,自己页面跳转自己页面需要在前面加上/,或者直接不写action-->
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>部门标题</label>
                        <input type="text" name="title" class="form-control" placeholder="部门标题">
                    </div>
                    <button type="submit" class="btn btn-primary">保存</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

staff_project/staff_app/templates/department_edit.html
{% extends 'layout.html' %}
{% block content %}
<!--新建部门-->
<div>
    <div class="container">
        <!--面板里面套表单-->
        <div class="panel panel-default">
            <div class="panel-heading">修改部门</div>
            <div class="panel-body">
                <!--这是表单,,自己页面跳转自己页面需要在前面加上/,或者直接不写action-->
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>部门标题</label>
                        <!--value="{{row_object.title}}添加默认值-->
                        <input type="text"name="title" class="form-control" placeholder="部门标题" value="{{row_object.title}}">
                    </div>
                    <button type="submit" class="btn btn-primary">保存</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

staff_project/staff_app/templates/error.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div class="alert alert-danger" role="alert">{{msg}}</div>
</div>
{% endblock%}

staff_project/staff_app/templates/good_add.html
{% extends 'layout.html' %}
{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建商品 </h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

staff_project/staff_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../static/plugins/bootstrap-3.4.1/css/bootstrap.css">
    <style>
    .container{
    width:500px;
    border:1px solid black;
    margin-top:150px;
    padding:20px 20px 60px 20px;
    border-radius:20px;
    box-shadow:26px 29px 23px #333;

    }
    .login{
    text-align:center;
    }


    </style>
</head>

<body>
<div class="container">
    <!--    novalidata是关闭前端浏览器做校验-->
    <form method="post" novalidate>
        {% csrf_token %}
        <h2 class="login">登录</h2>
        <!--用户名-->
        <div class="form-group">
            <label>用户名</label>
            {{form.username}}
            <span style="color:red;">{{form.username.errors.0}}</span>
        </div>
        <!--密码-->
        <div class="form-group">
            <label>密码</label>
            {{form.password}}
            <span style="color:red;">{{form.password.errors.0}}</span>
        </div>
        <!--图片验证码-->
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image_code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-info">登 录</button>
    </form>
</div>
</body>
</html>

staff_project/staff_app/templates/mobile_list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
    <div style="margin-bottom: 10px" class="clearfix">
        <a class="btn btn-success" href="/mobile_add/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建靓号
        </a>
        <div style="float:right;width:400px;">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="num" class="form-control" placeholder="Search for..."
                           value="{{search_data}}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            用户列表
        </div>

        <!-- 表格部分 -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
            <tr>
                <th>{{ obj.id }}</th>
                <td>{{ obj.mobile }}</td>
                <td>{{ obj.price }}</td>
                <td>{{ obj.get_level_display }}</td>
                <td>{{ obj.get_status_display }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/mobile_edit/{{ obj.id }}">编辑</a>
                    <a class="btn btn-danger btn-xs" href="/mobile_delete/{{ obj.id }}">删除</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div style="clearfix">
        <ul class="pagination">
            {{page_string}}
        </ul>
    </div>
</div>
{% endblock %}

staff_project/staff_app/templates/modelform_staff_add.html
{% extends 'layout.html' %}
{% block content %}
{% block css %}
<link rel="stylesheet" href="../static/plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.css">
{% endblock %}
<!--新建员工-->
<div>
    <div class="container">
        <!--面板里面套表单-->
        <div class="panel panel-default">
            <div class="panel-heading">新建员工</div>
            <div class="panel-body">
                <!--这是表单,,自己页面跳转自己页面需要在前面加上/,或者直接不写action-->
                <!--novalidate关闭浏览器做的检验-->
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group ">
                        <label>{{field.label}}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>
<!--                        <input type="text" class="form-control" placeholder="姓名" name="name">-->
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">保存</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="../static/plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js"></script>
<script src="../static/plugins/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>

<script>
    $(function(){

    $("#id_entry_time").datetimepicker({
        format: "yyyy-mm-dd",
        showMeridian: true,
        autoclose: true,
        todayBtn: true,
        language:"zh-CN"
    });

    })
</script>
{% endblock %}

staff_project/staff_app/templates/staff_list.html
{% extends 'layout.html' %}
{% block content %}
<div>
    <div class="container">
        <!--按钮区域-->
        <div style="margin-bottom:10px;">
            <a class="btn btn-success" href="/staff_add/">
                <!--新建部门前有一个小图标-->
                <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span>
                新建用户
            </a>
            <a class="btn btn-success" href="/modelform_staff_add/">
                <!--新建部门前有一个小图标-->
                <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span>
                ModelForm新建用户
            </a>
        </div>
        <!--面板里面套表格-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <!--用户列表前有一个小图标-->
                <span class="glyphicon glyphicon-align-justify" aria-hidden="true"> </span>
                用户列表
            </div>
            <!--表格区域-->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>工资</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in data_list %}
                <tr>
                    <th scope="row">{{obj.id}}</th>
                    <td>{{obj.name}}</td>
                    <td>{{obj.password}}</td>
                    <td>{{obj.age}}</td>
                    <td>{{obj.salary}}</td>
                    <td>{{obj.entry_time|date:"Y-m-d"}}</td>
                    <td>{{obj.get_gender_display}}</td>
                    <td>{{obj.staff_department.title}}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/staff_edit/{{obj.id}}">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/staff_delete/{{obj.id}}">删除</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{page_string}}
        </ul>
    </div>
</div>
{% endblock %}